export * from './Film/Film'
// export * from './FilmDetails/FilmDetails'
export * from './FilmGenres/FilmGenres'
export * from './Films/Films'
export * from './FormSearch/FormSearch'
export * from './Genre/Genre'
// export * from './GenreInDetails/GenreInDetails'
export * from './Genres/Genres'
export * from './Header/Header'
// export * from './QueryFilms/QueryFilms'
export * from './Sidebar/Sidebar'

